prepare_part1:
	gfortran -o part1 part1.f90 

prepare_part2:
	gfortran -o part2 part2.f90 


run_part1:
	./part1

run_part2:
	./part2


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
