prepare_part1:
	python create_schematic.py

prepare_part2:
	echo "Preparing part 2"


run_part1:
	echo "Start minecraft, load the world, activate the structure blocks and start the program by placing a redstone block by the command block labeled \"Process kernel step (border=black)\""

run_part2:
	echo "Running part 2"


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
