prepare_part1:
	echo "Preparing part 1"

prepare_part2:
	echo "Preparing part 2"


run_part1:
	lua part1.lua

run_part2:
	lua part2.lua


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
