prepare_part1:
	scalac part1.scala

prepare_part2:
	scalac part2.scala


run_part1:
	scala Day14Part1

run_part2:
	scala Day14Part2


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
