prepare_part1:
	echo "no preparation needed"

prepare_part2:
	echo "no preparation needed"


run_part1:
	./fish.py part1.fsh

run_part2:
	./fish.py part2.fsh


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
