prepare_part1:
	pip install -r requirements.txt

prepare_part2:
	pip install -r requirements.txt


run_part1:
	python part1.py

run_part2:
	python part2.py


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
