prepare_part1:
	cargo build --release

prepare_part2:
	echo "Preparing part 2"


run_part1:
	./target/release/part1

run_part2:
	echo "Running part 2"


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
