prepare_part1:
	echo "Preparing part 1"

prepare_part2:
	echo "Preparing part 2"


run_part1:
	julia part1.jl

run_part2:
	julia part2.jl


part1: | prepare_part1 run_part1
part2: | prepare_part2 run_part2
